/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ClienteMyn;
import bean.FuncionarioMyn;
import bean.ProdutoMyn;
import bean.VendaprodutoMyn;
import bean.VendasMyn;
import bean.VendasProdutos;
import controles.VendaProdutoControle;
import dao.ClienteMynDAO;
import dao.FuncionarioMynDAO;
import dao.ProdutoMynDAO;
import dao.VendaProdutoMynDAO;
import dao.VendasMynDAO;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author u71665822198
 */
public class JDlgVendas extends javax.swing.JDialog {

    MaskFormatter mascaraData;

    private boolean incluindo;


    public VendasMyn venda;
    public VendasMynDAO VendasMynDAO;
    public FuncionarioMynDAO funcionarioMynDAO;
    public FuncionarioMyn funcionario;
    public ProdutoMynDAO produtoMynDAO;
    public VendaProdutoMynDAO vendaProdutoMynDAO;
    public VendaprodutoMyn vendaProdutoMyn;
    public JDlgVendasProduto jDlgVendasProduto;
    public VendaProdutoControle vendaProdutoControle;

    /**
     * Creates new form JDlgVendas
     */
    public JDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Venda");
        setLocationRelativeTo(null);

        VendasMynDAO = new VendasMynDAO();

        Util.habilitar(false, jTxtCodigo, jFmtData, jCboCliente, jCboFuncionario, jTxtTempoE, jTxtValor, jBtnCancelar, jBtnCancelar, jBtnConfirmar);
        Util.habilitar(true, jBtnExcluir, jBtnIncluir, jBtnAlterar, jBtnPesquisar);
        Util.limparCampos(jTxtCodigo, jFmtData, jCboCliente, jCboFuncionario, jTxtTempoE, jTxtValor);

        ClienteMynDAO clienteMynDAO = new ClienteMynDAO();
        List listaCbo = clienteMynDAO.listAll();
        for (int i = 0; i < listaCbo.size(); i++) {
            jCboCliente.addItem((ClienteMyn) listaCbo.get(i));
        }

        FuncionarioMynDAO funcionarioMynDAO = new FuncionarioMynDAO();
        List listaCba = funcionarioMynDAO.listAll();
        for (int i = 0; i < listaCba.size(); i++) {
            jCboFuncionario.addItem((FuncionarioMyn) listaCba.get(i));
        }

        vendaProdutoControle = new VendaProdutoControle();
        jTable1.setModel(vendaProdutoControle);
        try {
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtData.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
    }

    public VendasMyn viewBean() {
        VendasMyn vendasMyn = new VendasMyn();
        vendasMyn.setIdVendasMyn(Integer.parseInt(jTxtCodigo.getText()));
        vendasMyn.setTempoEntregaMyn(jTxtTempoE.getText());
        vendasMyn.setDataMyn(Util.strDate(jFmtData.getText()));
        vendasMyn.setValorMyn(Util.strDouble(jTxtValor.getText()));
        vendasMyn.setClienteMyn((ClienteMyn) jCboCliente.getSelectedItem());
        vendasMyn.setFuncionarioMyn((FuncionarioMyn) jCboFuncionario.getSelectedItem());
        return vendasMyn;
    }

    public void beanView(VendasMyn vendasMyn) {
        jTxtCodigo.setText(Util.intStr(vendasMyn.getIdVendasMyn()));
        jTxtTempoE.setText((vendasMyn.getTempoEntregaMyn()));
        jTxtValor.setText(Util.doubleStr(vendasMyn.getValorMyn()));
        jFmtData.setText(Util.dateStr(vendasMyn.getDataMyn()));
        jCboCliente.setSelectedItem(vendasMyn.getClienteMyn());
        jCboFuncionario.setSelectedItem(vendasMyn.getFuncionarioMyn());
        vendaProdutoMynDAO = new VendaProdutoMynDAO();
        List listaVendas = (List) vendaProdutoMynDAO.listProdutoMyn(vendasMyn);

        vendaProdutoControle.setList(listaVendas);
    }

    public int getSelectedRowProd() {
        return jTable1.getSelectedRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtTempoE = new javax.swing.JTextField();
        jTxtValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtData = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCboCliente = new javax.swing.JComboBox<ClienteMyn>();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnIncluirProd = new javax.swing.JButton();
        jBtnAlterarProd = new javax.swing.JButton();
        jBtnExcluirProd = new javax.swing.JButton();
        jCboFuncionario = new javax.swing.JComboBox<FuncionarioMyn>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Tempo de entrega");

        jLabel3.setText("Valor");

        jLabel4.setText("Data");

        jLabel5.setText("Funcionario");

        jLabel6.setText("Cliente");

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/incluir.png"))); // NOI18N
        jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirProdActionPerformed(evt);
            }
        });

        jBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/alterar.png"))); // NOI18N
        jBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarProdActionPerformed(evt);
            }
        });

        jBtnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/Excluir.png"))); // NOI18N
        jBtnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTxtTempoE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jCboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jBtnPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIncluirProd)
                            .addComponent(jBtnAlterarProd)
                            .addComponent(jBtnExcluirProd))
                        .addGap(0, 31, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTempoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(6, 6, 6)
                            .addComponent(jCboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(6, 6, 6)
                            .addComponent(jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluirProd)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnAlterarProd)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnExcluirProd)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIncluir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAlterar)
                        .addComponent(jBtnExcluir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnPesquisar)
                        .addComponent(jBtnConfirmar)
                        .addComponent(jBtnCancelar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        venda = viewBean();
        vendaProdutoMynDAO = new VendaProdutoMynDAO();

        if (incluindo) {
            VendasMynDAO.insert(venda);
            VendaProdutoMynDAO vendaProdutoMynDAO = new VendaProdutoMynDAO();
            VendaprodutoMyn vendaProduto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                vendaProduto = vendaProdutoControle.getBean(linha);
                vendaProduto.setVendasMyn(venda);
                vendaProdutoMynDAO.insert(vendaProduto);
            }
        } else {
            VendasMynDAO.update(venda);
            VendaProdutoMynDAO vendaProdutoMynDAO = new VendaProdutoMynDAO();
            VendaprodutoMyn vendaProduto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                vendaProduto = vendaProdutoControle.getBean(linha);
                vendaProduto.setVendasMyn(venda);
                vendaProdutoMynDAO.delete(vendaProduto);
            }

            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                VendaprodutoMyn vendaProduto1 = vendaProdutoControle.getBean(linha);
                vendaProduto1.setVendasMyn(venda);
                vendaProdutoMynDAO.insert(vendaProduto1);
            }

        }
        
        Util.habilitar(false, jTxtCodigo, jTxtTempoE, jTxtValor, jFmtData, jCboCliente, jCboFuncionario, jBtnConfirmar, jBtnCancelar, jBtnAlterarProd, jBtnIncluirProd, jBtnExcluirProd);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
        Util.limparCampos(jTxtCodigo, jTxtTempoE, jTxtValor, jFmtData, jCboCliente, jCboFuncionario, jTable1);
        vendaProdutoControle.setList(new ArrayList());

        venda = null;
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        Util.habilitar(false, jTxtCodigo, jTxtTempoE, jTxtValor, jFmtData, jCboCliente, jCboFuncionario, jBtnConfirmar, jBtnCancelar, jBtnAlterarProd, jBtnIncluirProd, jBtnExcluirProd);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
        Util.limparCampos(jTxtCodigo, jTxtTempoE, jTxtValor, jFmtData, jCboCliente, jCboFuncionario, jTable1);
        vendaProdutoControle.setList(new ArrayList());
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        JDlgVendasPesquisa jDlgVendasPesquisa = new JDlgVendasPesquisa(null, true);
        jDlgVendasPesquisa.setTelaAnterior(this);
        jDlgVendasPesquisa.setVisible(true);
        Util.habilitar(true, jBtnCancelar, jBtnAlterar, jBtnExcluir, jBtnConfirmar);
        Util.habilitar(false, jBtnIncluir, jBtnAlterarProd, jBtnIncluirProd, jBtnExcluirProd);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.habilitar(true, jTxtCodigo, jTxtTempoE, jTxtValor, jFmtData, jCboCliente, jCboFuncionario, jBtnConfirmar, jBtnCancelar, jBtnAlterarProd, jBtnIncluirProd, jBtnExcluirProd);
        Util.habilitar(false, jBtnExcluir, jBtnIncluir, jBtnAlterar, jBtnPesquisar);

        Util.limparCampos(jTxtCodigo, jTxtTempoE, jTxtValor, jFmtData, jCboCliente, jCboFuncionario);

        vendaProdutoControle.setList(new ArrayList());
        jTxtCodigo.grabFocus();
        incluindo = true;
        venda = new VendasMyn();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
         venda = viewBean();
        if (venda != null) {
            Util.habilitar(true, jBtnAlterarProd, jBtnIncluirProd, jBtnExcluirProd, jTable1);
            incluindo = false;
        } else {
            Util.mensagem("Precisa ser feita uma pesquisa");
        }
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        venda = viewBean();
        if (venda != null) {
            if (Util.perguntar("Deseja excluir a Venda?") == true) {
                vendaProdutoMynDAO = new VendaProdutoMynDAO();
                VendaprodutoMyn vendaProduto;
                for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                    vendaProduto = vendaProdutoControle.getBean(linha);
                    vendaProdutoMynDAO.delete(vendaProduto);
                }
                vendaProdutoMynDAO.delete(venda);
            }
        } else {
            Util.mensagem("Exclusão Cancelada");
        }
        vendaProdutoControle.setList(new ArrayList());
        Util.limparCampos(jTxtCodigo, jTxtTempoE, jTxtValor, jFmtData, jCboCliente, jCboFuncionario, jTable1);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
        Util.habilitar(false, jTxtCodigo, jTxtTempoE, jTxtValor, jFmtData, jCboCliente, jCboFuncionario, jBtnCancelar, jBtnCancelar, jBtnConfirmar, jBtnAlterar, jBtnExcluir, jBtnAlterarProd, jBtnIncluirProd, jBtnExcluirProd);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirProdActionPerformed
        JDlgVendasProduto jDlgVendasProduto = new JDlgVendasProduto(null, true);
        jDlgVendasProduto.setTitle("Inclusão de Produtos");
        jDlgVendasProduto.setTelaAnterior(this);
        jDlgVendasProduto.setVisible(true);

    }//GEN-LAST:event_jBtnIncluirProdActionPerformed

    private void jBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarProdActionPerformed
        jDlgVendasProduto = new JDlgVendasProduto(null, true);
        jDlgVendasProduto.setTitle("Alteração de produtos");
        jDlgVendasProduto.setTelaAnterior(this);
        int linSel = jTable1.getSelectedRow();
        VendaprodutoMyn vendaProdutoMyn = (VendaprodutoMyn) vendaProdutoControle.getBean(linSel);
        jDlgVendasProduto.beanView(vendaProdutoMyn);
        jDlgVendasProduto.setVisible(true);
    }//GEN-LAST:event_jBtnAlterarProdActionPerformed

    private void jBtnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirProdActionPerformed
        int selectedRow = getSelectedRowProd();
        if (selectedRow == -1) {
            Util.mensagem("Selecione a linha");
        } else {
            if (Util.perguntar("Confirmar Exclusão do produto") == true) {
                VendaprodutoMyn vendaProdutoMyn = vendaProdutoControle.getBean(selectedRow);
                vendaProdutoControle.removeBean(selectedRow);
                if (vendaProdutoMyn != null) {
                    vendaProdutoMynDAO.delete(vendaProdutoMyn);
                }
            }
        }
    }//GEN-LAST:event_jBtnExcluirProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas dialog = new JDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterarProd;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluirProd;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirProd;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<ClienteMyn> jCboCliente;
    private javax.swing.JComboBox<FuncionarioMyn> jCboFuncionario;
    private javax.swing.JFormattedTextField jFmtData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtTempoE;
    private javax.swing.JTextField jTxtValor;
    // End of variables declaration//GEN-END:variables
}
