package bean;
// Generated 16/09/2023 14:42:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuncionarioMyn generated by hbm2java
 */
@Entity
@Table(name="funcionario_myn"
    ,catalog="db_marcelo_nakasima"
)
public class FuncionarioMyn  implements java.io.Serializable {


     private int idFuncionarioMyn;
     private String nomeMyn;
     private String emailMyn;
     private String telefoneMyn;
     private String enderecoMyn;
     private String cpfMyn;
     private String rgMyn;
     private Date dataNascimentoMyn;
     private Date dataAdmissaoMyn;
     private Set vendasMyns = new HashSet(0);    public FuncionarioMyn getIdFuncionario_myn;


    public FuncionarioMyn() {
    }

	
    public FuncionarioMyn(int idFuncionarioMyn, String nomeMyn, String emailMyn, String telefoneMyn, String enderecoMyn, String cpfMyn, String rgMyn, Date dataNascimentoMyn, Date dataAdmissaoMyn) {
        this.idFuncionarioMyn = idFuncionarioMyn;
        this.nomeMyn = nomeMyn;
        this.emailMyn = emailMyn;
        this.telefoneMyn = telefoneMyn;
        this.enderecoMyn = enderecoMyn;
        this.cpfMyn = cpfMyn;
        this.rgMyn = rgMyn;
        this.dataNascimentoMyn = dataNascimentoMyn;
        this.dataAdmissaoMyn = dataAdmissaoMyn;
    }
    public FuncionarioMyn(int idFuncionarioMyn, String nomeMyn, String emailMyn, String telefoneMyn, String enderecoMyn, String cpfMyn, String rgMyn, Date dataNascimentoMyn, Date dataAdmissaoMyn, Set vendasMyns) {
       this.idFuncionarioMyn = idFuncionarioMyn;
       this.nomeMyn = nomeMyn;
       this.emailMyn = emailMyn;
       this.telefoneMyn = telefoneMyn;
       this.enderecoMyn = enderecoMyn;
       this.cpfMyn = cpfMyn;
       this.rgMyn = rgMyn;
       this.dataNascimentoMyn = dataNascimentoMyn;
       this.dataAdmissaoMyn = dataAdmissaoMyn;
       this.vendasMyns = vendasMyns;
    }
   
     @Id 

    
    @Column(name="idFuncionario_myn", unique=true, nullable=false)
    public int getIdFuncionarioMyn() {
        return this.idFuncionarioMyn;
    }
    
    public void setIdFuncionarioMyn(int idFuncionarioMyn) {
        this.idFuncionarioMyn = idFuncionarioMyn;
    }

    
    @Column(name="nome_myn", nullable=false, length=45)
    public String getNomeMyn() {
        return this.nomeMyn;
    }
    
    public void setNomeMyn(String nomeMyn) {
        this.nomeMyn = nomeMyn;
    }

    
    @Column(name="email_myn", nullable=false, length=45)
    public String getEmailMyn() {
        return this.emailMyn;
    }
    
    public void setEmailMyn(String emailMyn) {
        this.emailMyn = emailMyn;
    }

    
    @Column(name="telefone_myn", nullable=false, length=45)
    public String getTelefoneMyn() {
        return this.telefoneMyn;
    }
    
    public void setTelefoneMyn(String telefoneMyn) {
        this.telefoneMyn = telefoneMyn;
    }

    
    @Column(name="endereco_myn", nullable=false, length=45)
    public String getEnderecoMyn() {
        return this.enderecoMyn;
    }
    
    public void setEnderecoMyn(String enderecoMyn) {
        this.enderecoMyn = enderecoMyn;
    }

    
    @Column(name="cpf_myn", nullable=false, length=45)
    public String getCpfMyn() {
        return this.cpfMyn;
    }
    
    public void setCpfMyn(String cpfMyn) {
        this.cpfMyn = cpfMyn;
    }

    
    @Column(name="rg_myn", nullable=false, length=45)
    public String getRgMyn() {
        return this.rgMyn;
    }
    
    public void setRgMyn(String rgMyn) {
        this.rgMyn = rgMyn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_myn", nullable=false, length=10)
    public Date getDataNascimentoMyn() {
        return this.dataNascimentoMyn;
    }
    
    public void setDataNascimentoMyn(Date dataNascimentoMyn) {
        this.dataNascimentoMyn = dataNascimentoMyn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataAdmissao_myn", nullable=false, length=10)
    public Date getDataAdmissaoMyn() {
        return this.dataAdmissaoMyn;
    }
    
    public void setDataAdmissaoMyn(Date dataAdmissaoMyn) {
        this.dataAdmissaoMyn = dataAdmissaoMyn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionarioMyn")
    public Set getVendasMyns() {
        return this.vendasMyns;
    }
    
    public void setVendasMyns(Set vendasMyns) {
        this.vendasMyns = vendasMyns;
    }

    public FuncionarioMyn getIdFuncionario_myn() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


