package bean;
// Generated 21/09/2023 18:10:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutoMyn generated by hbm2java
 */
@Entity
@Table(name="produto_myn"
    ,catalog="db_marcelo_nakasima"
)
public class ProdutoMyn  implements java.io.Serializable {


     private int idProdutoMyn;
     private String nomeMyn;
     private String descricaoMyn;
     private double valorMyn;
     private int tamanhoMyn;
     private int categoriaMyn;
     

    public ProdutoMyn() {
    }

	
    public ProdutoMyn(int idProdutoMyn, String nomeMyn, String descricaoMyn, double valorMyn, int tamanhoMyn, int categoriaMyn) {
        this.idProdutoMyn = idProdutoMyn;
        this.nomeMyn = nomeMyn;
        this.descricaoMyn = descricaoMyn;
        this.valorMyn = valorMyn;
        this.tamanhoMyn = tamanhoMyn;
        this.categoriaMyn = categoriaMyn;
    }
    public ProdutoMyn(int idProdutoMyn, String nomeMyn, String descricaoMyn, double valorMyn, int tamanhoMyn, int categoriaMyn, Set vendaprodutoMyns) {
       this.idProdutoMyn = idProdutoMyn;
       this.nomeMyn = nomeMyn;
       this.descricaoMyn = descricaoMyn;
       this.valorMyn = valorMyn;
       this.tamanhoMyn = tamanhoMyn;
       this.categoriaMyn = categoriaMyn;
     
    }
   
     @Id 

    
    @Column(name="idProduto_myn", unique=true, nullable=false)
    public int getIdProdutoMyn() {
        return this.idProdutoMyn;
    }
    
    public void setIdProdutoMyn(int idProdutoMyn) {
        this.idProdutoMyn = idProdutoMyn;
    }

    
    @Column(name="nome_myn", nullable=false, length=45)
    public String getNomeMyn() {
        return this.nomeMyn;
    }
    
    public void setNomeMyn(String nomeMyn) {
        this.nomeMyn = nomeMyn;
    }

    
    @Column(name="descricao_myn", nullable=false, length=150)
    public String getDescricaoMyn() {
        return this.descricaoMyn;
    }
    
    public void setDescricaoMyn(String descricaoMyn) {
        this.descricaoMyn = descricaoMyn;
    }

    
    @Column(name="valor_myn", nullable=false, precision=22, scale=0)
    public double getValorMyn() {
        return this.valorMyn;
    }
    
    public void setValorMyn(double valorMyn) {
        this.valorMyn = valorMyn;
    }

    
    @Column(name="tamanho_myn", nullable=false)
    public int getTamanhoMyn() {
        return this.tamanhoMyn;
    }
    
    public void setTamanhoMyn(int tamanhoMyn) {
        this.tamanhoMyn = tamanhoMyn;
    }

    
    @Column(name="categoria_myn", nullable=false)
    public int getCategoriaMyn() {
        return this.categoriaMyn;
    }
    
    public void setCategoriaMyn(int categoriaMyn) {
        this.categoriaMyn = categoriaMyn;
    }

}


