package bean;
// Generated 21/09/2023 18:10:17 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosMyn generated by hbm2java
 */
@Entity
@Table(name="usuarios_myn"
    ,catalog="db_marcelo_nakasima"
)
public class UsuariosMyn  implements java.io.Serializable {


     private int idUsuariosMyn;
     private String nomeMyn;
     private String apelidoMyn;
     private String cpfMyn;
     private Date dataNascimentoMyn;
     private String senhaMyn;
     private int nivelMyn;
     private String ativoMyn;

    public UsuariosMyn() {
    }

    public UsuariosMyn(int idUsuariosMyn, String nomeMyn, String apelidoMyn, String cpfMyn, Date dataNascimentoMyn, String senhaMyn, int nivelMyn, String ativoMyn) {
       this.idUsuariosMyn = idUsuariosMyn;
       this.nomeMyn = nomeMyn;
       this.apelidoMyn = apelidoMyn;
       this.cpfMyn = cpfMyn;
       this.dataNascimentoMyn = dataNascimentoMyn;
       this.senhaMyn = senhaMyn;
       this.nivelMyn = nivelMyn;
       this.ativoMyn = ativoMyn;
    }
   
     @Id 

    
    @Column(name="idUsuarios_myn", unique=true, nullable=false)
    public int getIdUsuariosMyn() {
        return this.idUsuariosMyn;
    }
    
    public void setIdUsuariosMyn(int idUsuariosMyn) {
        this.idUsuariosMyn = idUsuariosMyn;
    }

    
    @Column(name="nome_myn", nullable=false, length=45)
    public String getNomeMyn() {
        return this.nomeMyn;
    }
    
    public void setNomeMyn(String nomeMyn) {
        this.nomeMyn = nomeMyn;
    }

    
    @Column(name="apelido_myn", nullable=false, length=45)
    public String getApelidoMyn() {
        return this.apelidoMyn;
    }
    
    public void setApelidoMyn(String apelidoMyn) {
        this.apelidoMyn = apelidoMyn;
    }

    
    @Column(name="cpf_myn", nullable=false, length=45)
    public String getCpfMyn() {
        return this.cpfMyn;
    }
    
    public void setCpfMyn(String cpfMyn) {
        this.cpfMyn = cpfMyn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_myn", nullable=false, length=10)
    public Date getDataNascimentoMyn() {
        return this.dataNascimentoMyn;
    }
    
    public void setDataNascimentoMyn(Date dataNascimentoMyn) {
        this.dataNascimentoMyn = dataNascimentoMyn;
    }

    
    @Column(name="senha_myn", nullable=false, length=45)
    public String getSenhaMyn() {
        return this.senhaMyn;
    }
    
    public void setSenhaMyn(String senhaMyn) {
        this.senhaMyn = senhaMyn;
    }

    
    @Column(name="nivel_myn", nullable=false)
    public int getNivelMyn() {
        return this.nivelMyn;
    }
    
    public void setNivelMyn(int nivelMyn) {
        this.nivelMyn = nivelMyn;
    }

    
    @Column(name="ativo_myn", nullable=false, length=1)
    public String getAtivoMyn() {
        return this.ativoMyn;
    }
    
    public void setAtivoMyn(String ativoMyn) {
        this.ativoMyn = ativoMyn;
    }




}


