package bean;
// Generated 21/09/2023 18:10:17 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasMyn generated by hbm2java
 */
@Entity
@Table(name="vendas_myn"
    ,catalog="db_marcelo_nakasima"
)
public class VendasMyn  implements java.io.Serializable {


     private int idVendasMyn;
     private ClienteMyn clienteMyn;
     private FuncionarioMyn funcionarioMyn;
     private String nomeProdutoMyn;
     private double valorMyn;
     private Date dataMyn;

    public VendasMyn() {
    }

    public VendasMyn(int idVendasMyn, ClienteMyn clienteMyn, FuncionarioMyn funcionarioMyn, String nomeProdutoMyn, double valorMyn, Date dataMyn) {
       this.idVendasMyn = idVendasMyn;
       this.clienteMyn = clienteMyn;
       this.funcionarioMyn = funcionarioMyn;
       this.nomeProdutoMyn = nomeProdutoMyn;
       this.valorMyn = valorMyn;
       this.dataMyn = dataMyn;
    }
   
     @Id 

    
    @Column(name="idVendas_myn", unique=true, nullable=false)
    public int getIdVendasMyn() {
        return this.idVendasMyn;
    }
    
    public void setIdVendasMyn(int idVendasMyn) {
        this.idVendasMyn = idVendasMyn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Cliente_myn", nullable=false)
    public ClienteMyn getClienteMyn() {
        return this.clienteMyn;
    }
    
    public void setClienteMyn(ClienteMyn clienteMyn) {
        this.clienteMyn = clienteMyn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Funcionario_myn", nullable=false)
    public FuncionarioMyn getFuncionarioMyn() {
        return this.funcionarioMyn;
    }
    
    public void setFuncionarioMyn(FuncionarioMyn funcionarioMyn) {
        this.funcionarioMyn = funcionarioMyn;
    }

    
    @Column(name="nomeProduto_myn", nullable=false, length=45)
    public String getNomeProdutoMyn() {
        return this.nomeProdutoMyn;
    }
    
    public void setNomeProdutoMyn(String nomeProdutoMyn) {
        this.nomeProdutoMyn = nomeProdutoMyn;
    }

    
    @Column(name="valor_myn", nullable=false, precision=22, scale=0)
    public double getValorMyn() {
        return this.valorMyn;
    }
    
    public void setValorMyn(double valorMyn) {
        this.valorMyn = valorMyn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_myn", nullable=false, length=10)
    public Date getDataMyn() {
        return this.dataMyn;
    }
    
    public void setDataMyn(Date dataMyn) {
        this.dataMyn = dataMyn;
    }




}


