package bean;
// Generated 07/12/2023 11:31:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaprodutoMyn generated by hbm2java
 */
@Entity
@Table(name="vendaproduto_myn"
    ,catalog="db_marcelo_nakasima"
)
public class VendaprodutoMyn  implements java.io.Serializable {


     private int idVendaProdutoMyn;
     private VendasMyn vendasMyn;
     private ProdutoMyn produtoMyn;
     private int quantidadeMyn;
     private double valorUnitarioMyn;

    public VendaprodutoMyn() {
    }

	
    public VendaprodutoMyn(int idVendaProdutoMyn, int quantidadeMyn, double valorUnitarioMyn) {
        this.idVendaProdutoMyn = idVendaProdutoMyn;
        this.quantidadeMyn = quantidadeMyn;
        this.valorUnitarioMyn = valorUnitarioMyn;
    }
    public VendaprodutoMyn(int idVendaProdutoMyn, VendasMyn vendasMyn, ProdutoMyn produtoMyn, int quantidadeMyn, double valorUnitarioMyn) {
       this.idVendaProdutoMyn = idVendaProdutoMyn;
       this.vendasMyn = vendasMyn;
       this.produtoMyn = produtoMyn;
       this.quantidadeMyn = quantidadeMyn;
       this.valorUnitarioMyn = valorUnitarioMyn;
    }
   
     @Id @GeneratedValue(strategy=GenerationType.IDENTITY)

    
    @Column(name="idVendaProduto_myn", unique=true, nullable=false)
    public int getIdVendaProdutoMyn() {
        return this.idVendaProdutoMyn;
    }
    
    public void setIdVendaProdutoMyn(int idVendaProdutoMyn) {
        this.idVendaProdutoMyn = idVendaProdutoMyn;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fk_Vendas_myn")
    public VendasMyn getVendasMyn() {
        return this.vendasMyn;
    }
    
    public void setVendasMyn(VendasMyn vendasMyn) {
        this.vendasMyn = vendasMyn;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fk_Produto_myn")
    public ProdutoMyn getProdutoMyn() {
        return this.produtoMyn;
    }
    
    public void setProdutoMyn(ProdutoMyn produtoMyn) {
        this.produtoMyn = produtoMyn;
    }

    
    @Column(name="quantidade_myn", nullable=false, length=45)
    public int getQuantidadeMyn() {
        return this.quantidadeMyn;
    }
    
    public void setQuantidadeMyn(int quantidadeMyn) {
        this.quantidadeMyn = quantidadeMyn;
    }

    
    @Column(name="valorUnitario_myn", nullable=false, precision=22, scale=0)
    public double getValorUnitarioMyn() {
        return this.valorUnitarioMyn;
    }
    
    public void setValorUnitarioMyn(double valorUnitarioMyn) {
        this.valorUnitarioMyn = valorUnitarioMyn;
    }




}


