package bean;
// Generated 16/09/2023 14:42:42 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaprodutoMyn generated by hbm2java
 */
@Entity
@Table(name="vendaproduto_myn"
    ,catalog="db_marcelo_nakasima"
)
public class VendaprodutoMyn  implements java.io.Serializable {


     private int idVendaProdutoMyn;
     private ProdutoMyn produtoMyn;
     private int quantidadeMyn;
     private String valorUnitarioMyn;

    public VendaprodutoMyn() {
    }

    public VendaprodutoMyn(int idVendaProdutoMyn, ProdutoMyn produtoMyn, int quantidadeMyn, String valorUnitarioMyn) {
       this.idVendaProdutoMyn = idVendaProdutoMyn;
       this.produtoMyn = produtoMyn;
       this.quantidadeMyn = quantidadeMyn;
       this.valorUnitarioMyn = valorUnitarioMyn;
    }
   
     @Id 

    
    @Column(name="idVendaProduto_myn", unique=true, nullable=false)
    public int getIdVendaProdutoMyn() {
        return this.idVendaProdutoMyn;
    }
    
    public void setIdVendaProdutoMyn(int idVendaProdutoMyn) {
        this.idVendaProdutoMyn = idVendaProdutoMyn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Produto_myn", nullable=false)
    public ProdutoMyn getProdutoMyn() {
        return this.produtoMyn;
    }
    
    public void setProdutoMyn(ProdutoMyn produtoMyn) {
        this.produtoMyn = produtoMyn;
    }

    
    @Column(name="quantidade_myn", nullable=false)
    public int getQuantidadeMyn() {
        return this.quantidadeMyn;
    }
    
    public void setQuantidadeMyn(int quantidadeMyn) {
        this.quantidadeMyn = quantidadeMyn;
    }

    
    @Column(name="valorUnitario_myn", nullable=false, length=45)
    public String getValorUnitarioMyn() {
        return this.valorUnitarioMyn;
    }
    
    public void setValorUnitarioMyn(String valorUnitarioMyn) {
        this.valorUnitarioMyn = valorUnitarioMyn;
    }




}


